#!/bin/sh

set -eu

fail() {
    printf 'Music to MIDI gateway startup failed: %s\n' "$*" >&2
    exit 2
}

require_env() {
    name="$1"
    eval "value=\${$name:-}"
    [ -n "$value" ] || fail "required environment variable $name is empty"
}

require_body_limit() {
    printf '%s\n' "$MAX_REQUEST_BODY_SIZE" \
        | grep -Eq '^[1-9][0-9]*(([KMGTPE]i?)?B)?$' \
        || fail "MAX_REQUEST_BODY_SIZE must be a positive byte size such as 4GiB"
}

mode="${MUSIC_TO_MIDI_GATEWAY_MODE:-public}"
case "$mode" in
    public)
        for name in PUBLIC_ADDRESS PUBLIC_ORIGIN ACME_EMAIL BASIC_AUTH_USER BASIC_AUTH_HASH MAX_REQUEST_BODY_SIZE; do
            require_env "$name"
        done
        printf '%s\n' "$PUBLIC_ADDRESS" \
            | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$' \
            || fail "PUBLIC_ADDRESS must be a public DNS hostname with valid labels and no scheme, path or port"
        printf '%s\n' "$ACME_EMAIL" \
            | grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$' \
            || fail "ACME_EMAIL must be a syntactically valid email address"
        case "$BASIC_AUTH_USER" in
            *[!A-Za-z0-9._-]*) fail "BASIC_AUTH_USER may contain only letters, digits, dot, underscore and hyphen" ;;
        esac
        case "$BASIC_AUTH_HASH" in
            *REPLACE_WITH*) fail "BASIC_AUTH_HASH still contains the example placeholder" ;;
        esac
        printf '%s\n' "$BASIC_AUTH_HASH" \
            | grep -Eq '^[$]argon2id[$]v=19[$]m=[1-9][0-9]*,t=[1-9][0-9]*,p=[1-9][0-9]*[$][A-Za-z0-9+/]+={0,2}[$][A-Za-z0-9+/]+={0,2}$' \
            || fail "BASIC_AUTH_HASH must be an Argon2id hash generated by caddy hash-password with complete encoded parameters"
        require_body_limit
        [ "$PUBLIC_ORIGIN" = "https://$PUBLIC_ADDRESS" ] \
            || fail "PUBLIC_ORIGIN must exactly equal https://PUBLIC_ADDRESS"
        config=/etc/caddy/Caddyfile
        ;;
    selfhost)
        require_env SELF_HOST_PORT
        require_env MAX_REQUEST_BODY_SIZE
        printf '%s\n' "$SELF_HOST_PORT" | grep -Eq '^[1-9][0-9]{0,4}$' \
            || fail "SELF_HOST_PORT must be an integer between 1 and 65535"
        [ "$SELF_HOST_PORT" -le 65535 ] \
            || fail "SELF_HOST_PORT must be an integer between 1 and 65535"
        require_body_limit
        config=/etc/caddy/Caddyfile.selfhost
        ;;
    *)
        fail "unsupported MUSIC_TO_MIDI_GATEWAY_MODE '$mode'; expected public or selfhost"
        ;;
esac

caddy validate --config "$config" --adapter caddyfile
exec caddy run --config "$config" --adapter caddyfile
