#!/bin/sh

set -eu

fail() {
    printf 'Music to MIDI gateway startup failed: %s\n' "$*" >&2
    exit 2
}

for name in PUBLIC_ADDRESS PUBLIC_ORIGIN ACME_EMAIL BASIC_AUTH_USER BASIC_AUTH_HASH MAX_REQUEST_BODY_SIZE; do
    eval "value=\${$name:-}"
    [ -n "$value" ] || fail "required environment variable $name is empty"
done

printf '%s\n' "$PUBLIC_ADDRESS" \
    | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$' \
    || fail "PUBLIC_ADDRESS must be a public DNS hostname with valid labels and no scheme, path or port"
printf '%s\n' "$ACME_EMAIL" \
    | grep -Eq '^[A-Za-z0-9._%+-]+@[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$' \
    || fail "ACME_EMAIL must be a syntactically valid email address"
case "$BASIC_AUTH_USER" in
    *[!A-Za-z0-9._-]*) fail "BASIC_AUTH_USER may contain only letters, digits, dot, underscore and hyphen" ;;
esac
case "$BASIC_AUTH_HASH" in
    *REPLACE_WITH*) fail "BASIC_AUTH_HASH still contains the example placeholder" ;;
esac
printf '%s\n' "$BASIC_AUTH_HASH" \
    | grep -Eq '^\$argon2id\$v=19\$m=[1-9][0-9]*,t=[1-9][0-9]*,p=[1-9][0-9]*\$[A-Za-z0-9+/]+={0,2}\$[A-Za-z0-9+/]+={0,2}$' \
    || fail "BASIC_AUTH_HASH must be an Argon2id hash generated by caddy hash-password with complete encoded parameters"
printf '%s\n' "$MAX_REQUEST_BODY_SIZE" \
    | grep -Eq '^[1-9][0-9]*(([KMGTPE]i?)?B)?$' \
    || fail "MAX_REQUEST_BODY_SIZE must be a positive byte size such as 4GiB"
[ "$PUBLIC_ORIGIN" = "https://$PUBLIC_ADDRESS" ] \
    || fail "PUBLIC_ORIGIN must exactly equal https://PUBLIC_ADDRESS"

caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
