"""Generate THIRD_PARTY_SBOM.txt for the frozen portable build environment.

The release workflow runs this after installing the exact pinned dependencies so
every published archive carries a complete software bill of materials: each
installed distribution with its version and declared license metadata.
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import sys


def _declared_license(dist: metadata.Distribution) -> str:
    meta = dist.metadata
    expression = (meta.get("License-Expression") or "").strip()
    if expression:
        return expression
    license_field = (meta.get("License") or "").strip()
    if license_field and license_field.lower() not in {"unknown", ""}:
        first_line = license_field.splitlines()[0].strip()
        if len(first_line) <= 80:
            return first_line
    classifiers = [
        value.split("::")[-1].strip()
        for value in meta.get_all("Classifier") or []
        if value.startswith("License") and "::" in value
    ]
    if classifiers:
        return ", ".join(sorted(set(classifiers)))
    return "UNKNOWN"


def generate_sbom(output_path: str) -> int:
    rows = []
    for dist in metadata.distributions():
        name = (dist.metadata.get("Name") or dist.name or "").strip()
        if not name:
            continue
        version = (dist.version or "").strip()
        license_label = _declared_license(dist)
        rows.append((name.lower(), f"{name}=={version} | license={license_label}"))
    rows.sort()
    lines = [
        "# Third-Party SBOM (frozen build environment)",
        "# Generated by tools/generate_third_party_sbom.py from importlib.metadata",
        "# Format: name==version | license=<declared license or UNKNOWN>",
        "",
        *(row for _key, row in rows),
        "",
    ]
    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    return len(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default="THIRD_PARTY_SBOM.txt",
        help="Output file path (default: THIRD_PARTY_SBOM.txt)",
    )
    args = parser.parse_args()
    count = generate_sbom(args.output)
    print(f"SBOM written to {args.output} with {count} distributions")
    if count == 0:
        print("error: no distributions found in the current environment", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
