"""Shared project terminology for Qt, Gradio, browser and command-line views."""

LABELS = {
    "zh_CN": {
        "title": "项目与批处理",
        "new": "新建项目",
        "open": "打开项目",
        "export": "导出项目包",
        "add": "添加歌曲",
        "apply": "应用当前设置",
        "run": "继续整个项目",
        "stop": "停止",
        "result": "打开歌曲结果",
        "profile_load": "导入工作流",
        "profile_save": "导出工作流",
        "empty": "添加歌曲后保存为项目；选择文件或模型不会启动处理。",
        "saved": "配置已保存，点击继续后执行。",
        "scope": "配置应用到",
        "all": "全部歌曲",
        "selected": "当前歌曲",
        "stems": "分离后转 MIDI 的声部与模型",
        "none": "仅分离 WAV",
        "pending": "待处理",
        "running": "处理中",
        "succeeded": "已完成",
        "failed": "失败",
        "cancelled": "已停止",
        "interrupted": "上次中断",
        "cancelling": "正在停止，等待当前推理结束",
        "name": "项目名称",
        "mode": "工作模式",
        "route": "转写模型",
        "files": "歌曲文件",
        "refresh": "刷新",
        "import": "导入项目包",
        "download": "下载文件",
        "song": "歌曲",
        "progress": "进度",
        "error": "项目操作失败",
        "save": "保存配置",
        "save_mix": "保存混音设置",
        "add_tracks": "添加音轨",
        "portable_hint": "项目自动保存。离开 Space 或 Colab 前导出项目包，可在其他运行环境导入继续。",
        "processing_hint": "正在执行，配置已锁定；停止会保留已完成的步骤。",
    },
    "en_US": {
        "title": "Projects and batch",
        "new": "New project",
        "open": "Open project",
        "export": "Export project",
        "add": "Add songs",
        "apply": "Apply current settings",
        "run": "Continue project",
        "stop": "Stop",
        "result": "Open song result",
        "profile_load": "Import workflow",
        "profile_save": "Export workflow",
        "empty": "Add songs to save a project. Selecting files or models does not start processing.",
        "saved": "Settings saved. Click Continue to process.",
        "scope": "Apply settings to",
        "all": "All songs",
        "selected": "Current song",
        "stems": "Stems and models for MIDI after separation",
        "none": "Separate WAV only",
        "pending": "Pending",
        "running": "Running",
        "succeeded": "Complete",
        "failed": "Failed",
        "cancelled": "Stopped",
        "interrupted": "Interrupted",
        "cancelling": "Stopping; waiting for active inference to end",
        "name": "Project name",
        "mode": "Mode",
        "route": "Transcription model",
        "files": "Audio files",
        "refresh": "Refresh",
        "import": "Import project",
        "download": "Download file",
        "song": "Song",
        "progress": "Progress",
        "error": "Project operation failed",
        "save": "Save settings",
        "save_mix": "Save mixer settings",
        "add_tracks": "Add tracks",
        "portable_hint": "Projects save automatically. Export a project archive before leaving Space or Colab to continue elsewhere.",
        "processing_hint": "Processing; settings are locked. Stopping preserves completed steps.",
    },
}


def labels(language: str = "zh_CN") -> dict[str, str]:
    return dict(LABELS["en_US" if language.startswith("en") else "zh_CN"])
